"""Add onupdate to ApplicationSession

Revision ID: b854a5d4f03e
Revises: 40d1a4d43c0a
Create Date: 2026-06-15 00:50:37.639213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b854a5d4f03e'
down_revision = '40d1a4d43c0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
