"""dead_letter_logging

Revision ID: fe5350529b37
Revises: 005
Create Date: 2026-06-15 01:56:22.887246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5350529b37'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_webhooks_id'), 'dead_letter_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_dead_letter_webhooks_session_id'), 'dead_letter_webhooks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letter_webhooks_session_id'), table_name='dead_letter_webhooks')
    op.drop_index(op.f('ix_dead_letter_webhooks_id'), table_name='dead_letter_webhooks')
    op.drop_table('dead_letter_webhooks')
    # ### end Alembic commands ###
